services:
  postgres:
    container_name: postgres_container
    image: postgres:latest
    environment:
      POSTGRES_USER: amir
      POSTGRES_PASSWORD: amir
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - application_network
  web:
    image: app_development_image:latest
    container_name: application_container
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.local
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    networks:
      - application_network
    depends_on:
      - postgres

volumes:
    postgres:
networks:
    application_network:
